### ISSUE TITLE
Give to the user the possibility to choose the likelihood to be used for inversion

### ISSUE THREAD

**Issue by pierrePalud** [pierrePalud/beetroots#7]
As of today, the user can only use one likelihood model in inversion of real data : the one mixing additive and multiplicative noises, and censorship (`beetroots.modelling.likelihoods.approx_censored_add_mult.py`).
In some contexts, a user could want to remove the additive noise or the multiplicative noise, or not to include censorship in the model.
There are already classes implementing these likelihoods in `beetroots.modelling.likelihoods`, it would be nice to be able to use them in inversion.

Where to apply changes: 
1) In the `input.yaml`, there could be parameters
```yaml
use_additive_noise: true
use_multiplicative_noise: true
use censorship: true
``` 
Or some parameters could become optional (that is, absent from the input file, or preferably set to `none`), such as the `filename_err` (for the additive noise standard deviation (std)) or the `sigma_m_float_linscale` (for the multiplicative noise std).

2) In the `SimulationRealDataNN` class (in `beetroots.simulations.astro.real_data.py`) : methods `setup()`, that calls
- the `setup_observation()` method  from the `SimulationRealData` class, to import the data, additive noise std, etc.
- the `setup_posteriors()` method from the `SimulationMySampler` class, to select the Likelihood class.

In this case : For now, the posterior is given a name `model_name = f"mixing_{i}"` (in `SimulationMySampler.setup_posteriors()`) that depend on the likelihood class. This could be generalized for other kinds of Likelihood classes, for clearer understanding of the sampling outputs.

---

The choice of the Likelihood class to use:

```yaml
use_additive_noise: true
use_multiplicative_noise: true
use censorship: true
``` 
-> `MixingModelsLikelihood` (from `beetroots.modelling.likelihoods.approx_censored_add_mult.py`)

```yaml
use_additive_noise: true
use_multiplicative_noise: true
use censorship: false
``` 
-> for now, `MixingModelsLikelihood` (need to define a simpler class ?)

```yaml
use_additive_noise: false
use_multiplicative_noise: true
use censorship: true
``` 
-> `CensoredLogNormalLikelihood` (from `beetroots.modelling.likelihoods.log_normal_censored.py`)

```yaml
use_additive_noise: false
use_multiplicative_noise: true
use censorship: false
``` 
-> `LogNormalLikelihood` (from `beetroots.modelling.likelihoods.log_normal.py`)

```yaml
use_additive_noise: true
use_multiplicative_noise: false
use censorship: true
``` 
-> `CensoredGaussianLikelihood` (from `beetroots.modelling.likelihoods.gaussian_censored.py`)

```yaml
use_additive_noise: true
use_multiplicative_noise: false
use censorship: false
``` 
-> `GaussianLikelihood` (from `beetroots.modelling.likelihoods.gaussian.py`)
