### ISSUE TITLE
Add possibility to accelerate the sampling results analysis by specifying the pixels to analyse (for 2D histograms, ESS computation, etc.)

### ISSUE THREAD

**Issue by pierrePalud** [pierrePalud/beetroots#8]
In the `input_params.yaml`, there is a (potentially empty) dictionary `pixels_of_interest` of (pixel index, pixel name) pairs. Currently, this dictionary is only used to highlight some pixels on observation or estimator maps - see in particular the `AbstractPlots2D._draw_rect_on_pixels_of_interest()` method.

For large maps of thousands of pixels, computing all the effective sample sizes (ESS) and plotting all the Markov chains and 2D sample histograms can be very slow, with runtimes sometimes comparable to the sampling itself. In this case, it is faster for the user to avoid these plots by setting

```yaml
run_params:
  mcmc:
    N_MCMC: ...
    T_MC: ...
    T_BI: ..
    plot_1D_chains: false
    plot_2D_chains: false
    plot_ESS: false
    plot_comparisons_yspace: false
```

and do them manually on a limited number of pixels after the sampling. 

For the user analysing large maps, it would be more efficient  if `beetroots` could perform the aforementioned results analysis only for the pixels indicated in `pixels_of_interest`, which can be set to `{}` if none of these plots is desired.

Suggestion of modifications:
- [ ] rename the options `plot_1D_chains` to `plot_all_1D_chains` and so on, to clarify that the user is choosing between drawing the figures for all pixels, or only for the pixels of interest.
- [ ] change the `ResultsExtractorMCMC` and `ResultsMC` classes to perform computations / drawing figures on the pixels of interest when the associated boolean is `False`.
